### ISSUE TITLE
Chat messages do not appear

### ISSUE THREAD

**Issue by skrtks** [pde-bakk/ft_transcendence#24] opened 2021-02-22 14:24 UTC
This might be the correct behavior, but I'm not sure. When I sent a message to another user but the other user has not opened the chat dialog yet, the message seems to be lost. Also when I refresh the page, the messages are lost.

**Comment by pde-bakk** [comment] 2021-02-22 16:43
Ah shit, this was something I had earlier and I fixed it, seems I broke it again. 
The root of the problem is that the message history is sent before you established your connection.
I'll fix it, thanks for checking, let's see how i broke it

**Comment by pde-bakk** [comment] 2021-02-27 15:15
Fixed in PR #19

**Closed by pde-bakk** 2021-02-27 15:15 UTC
